title: Blog by Florian Courgey
email: blog@floriancourgey.com
description: >- # this means to ignore newlines until "baseurl:"
  Curated list of tech tutorials on a wide variety of topics including PrestaShop,
  Adobe Campaign, Symfony, Angular, Django and much more!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.floriancourgey.com
permalink: /:year/:month/:title

# custom manifest.json
manifest:
  name: "Blog floriancourgey.com"
  short_name: "Blog fc.com"
  theme_color: "#2196f3"
  background_color: "#2196f3"
  display: "browser"
  scope: "/"
  start_url: "/"

disqus:
  shortname: floriancourgey

gtm: GTM-W6RKLQQ

# paginate plugin
paginate: 10
paginate_path: "/page-:num/"

collections:
  authors:
    output: true

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Florian Courgey"
      toc: true
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Florian Courgey"
      toc: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# algolia plugin
algolia:
  application_id: B5V7RM7VIT
  index_name:     jekyll
  settings:
    searchableAttributes:
      - title
      - headings
      - unordered(content)
      - collection
      - categories
      - tags

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - htmlproofer
